server:
  port: 8000
  auth_key:
  websocket: ws://60.205.170.189:8002/xiaozhi/v1/

selected_modules:
  llm: openai
  tts: edge
  asr: doubao_stream
  vad: silero

llm:
  type: openai
  api_key: sk-api-rSrjXYVb83qF88CWSg5Min9VkR6pgoVqUj4ZguxRAOef8D9nz7aC-tMPGyH5b_fwHFL8JqzNWVC9NWzceON1DeK09pP5SB0_gD7l4UWkcteAiTrK56qIuIs
  base_url: https://api.minimax.chat/v1/text/chatcompletion_v2
  model: abab6.5s-chat

tts:
  type: edge
  voice: zh-CN-XiaoxiaoNeural

asr:
  type: doubao_stream
  auth_method: apikey
  api_key: c0c9729b-2a33-45c7-88f0-736b855b9fc6
  appid: ""
  access_token: ""
  cluster: volcengine_streaming_common

vad:
  type: silero

log:
  level: INFO
  file: data/app.log

intent:
  type: function_call

memory:
  type: nomem
